import AppFooter from "@/components/common/AppFooter";
import AppNavbar from "@/components/common/AppNavbar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <AppNavbar />
      <main className="pt-[72px]">{children}</main>
      <AppFooter />
    </>
  );
}
